// Generated by Haxe 3.4.2
(function () { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw new js__$Boot_HaxeError("EReg::matched");
		}
	}
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.dateStr = function(date) {
	var m = date.getMonth() + 1;
	var d = date.getDate();
	var h = date.getHours();
	var mi = date.getMinutes();
	var s = date.getSeconds();
	return date.getFullYear() + "-" + (m < 10 ? "0" + m : "" + m) + "-" + (d < 10 ? "0" + d : "" + d) + " " + (h < 10 ? "0" + h : "" + h) + ":" + (mi < 10 ? "0" + mi : "" + mi) + ":" + (s < 10 ? "0" + s : "" + s);
};
HxOverrides.strDate = function(s) {
	var _g = s.length;
	switch(_g) {
	case 8:
		var k = s.split(":");
		var d = new Date();
		d["setTime"](0);
		d["setUTCHours"](k[0]);
		d["setUTCMinutes"](k[1]);
		d["setUTCSeconds"](k[2]);
		return d;
	case 10:
		var k1 = s.split("-");
		return new Date(k1[0],k1[1] - 1,k1[2],0,0,0);
	case 19:
		var k2 = s.split(" ");
		var y = k2[0].split("-");
		var t = k2[1].split(":");
		return new Date(y[0],y[1] - 1,y[2],t[0],t[1],t[2]);
	default:
		throw new js__$Boot_HaxeError("Invalid date format : " + s);
	}
};
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = true;
Lambda.exists = function(it,f) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			return true;
		}
	}
	return false;
};
Lambda.filter = function(it,f) {
	var l = new List();
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			l.add(x1);
		}
	}
	return l;
};
var List = function() {
	this.length = 0;
};
List.__name__ = true;
List.prototype = {
	add: function(item) {
		var x = new _$List_ListNode(item,null);
		if(this.h == null) {
			this.h = x;
		} else {
			this.q.next = x;
		}
		this.q = x;
		this.length++;
	}
	,push: function(item) {
		var x = new _$List_ListNode(item,this.h);
		this.h = x;
		if(this.q == null) {
			this.q = x;
		}
		this.length++;
	}
	,iterator: function() {
		return new _$List_ListIterator(this.h);
	}
};
var _$List_ListNode = function(item,next) {
	this.item = item;
	this.next = next;
};
_$List_ListNode.__name__ = true;
var _$List_ListIterator = function(head) {
	this.head = head;
};
_$List_ListIterator.__name__ = true;
_$List_ListIterator.prototype = {
	hasNext: function() {
		return this.head != null;
	}
	,next: function() {
		var val = this.head.item;
		this.head = this.head.next;
		return val;
	}
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	$("document").ready(Manager.init);
};
var Manager = function() { };
Manager.__name__ = true;
Manager.init = function(event) {
	Manager._jWindow = $(window);
	view_Login.init();
	view_SimpleBoard.init();
	view_ReportViewer.init();
	view_Information.init();
	view_StarChecker.init();
	jp_saken_js_ui_UI.setPagetop($("#pagetop").find("a"));
	ui_Keyboard.init();
	view_Login.start();
	var search = window.location.search;
	if(new EReg("specialmode=true","g").match(search)) {
		$("#all").addClass("specialmode");
	}
};
Manager.jWindow = function() {
	return Manager._jWindow;
};
Manager.login = function() {
	jp_saken_js_utils_Ajax.getDatetime(function(datetime) {
		Manager.visitDatetime = datetime;
		Manager.visitDate = Manager.visitDatetime.split(" ")[0];
		Manager.pastDate = jp_saken_common_utils_Handy.getPastDate(datetime,100);
		Manager.loadDB(Manager.onLoadedDB);
	});
};
Manager.logout = function() {
	if(!Manager._isLogined) {
		return;
	}
	utils_TimeKeeper.stop();
	view_Login.show();
	view_SimpleBoard.hide();
	view_ReportViewer.hide();
	view_StarChecker.hide();
};
Manager.reload = function() {
	utils_TimeKeeper.stop();
	view_ReportViewer.reset();
	Manager.login();
};
Manager.loadDB = function(onLoaded) {
	Manager._jWindow.on("loadDB",null,onLoaded);
	db_Members.load();
	db_Tasks.load(Manager.pastDate);
	db_Works.load();
	db_Clients.load();
};
Manager.onLoadedDB = function(event) {
	Manager._jWindow.unbind("loadDB",Manager.onLoadedDB);
	Manager._isLogined = true;
	view_Login.hide();
	view_SimpleBoard.show();
	view_ReportViewer.show();
	view_StarChecker.show();
	view_Information.run();
	utils_TimeKeeper.run();
};
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.getProperty = function(o,field) {
	var tmp;
	if(o == null) {
		return null;
	} else {
		var tmp1;
		if(o.__properties__) {
			tmp = o.__properties__["get_" + field];
			tmp1 = tmp;
		} else {
			tmp1 = false;
		}
		if(tmp1) {
			return o[tmp]();
		} else {
			return o[field];
		}
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
Reflect.deleteField = function(o,field) {
	if(!Object.prototype.hasOwnProperty.call(o,field)) {
		return false;
	}
	delete(o[field]);
	return true;
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var db_Clients = function() { };
db_Clients.__name__ = true;
db_Clients.load = function() {
	db_Database.load(db_Clients.db = [],"clients",db_Clients.COLUMN_LIST);
};
var db_Database = function() { };
db_Database.__name__ = true;
db_Database.load = function(db1,table,columns,where) {
	if(where == null) {
		where = "";
	}
	if(db_Database._counter == null) {
		db_Database._counter = 0;
	}
	db_Database._counter++;
	jp_saken_js_utils_Ajax.getData(table,columns,function(data) {
		var _g1 = 0;
		var _g = data.length;
		while(_g1 < _g) {
			var p = _g1++;
			var obj = data[p];
			db1[obj.id] = obj;
		}
		db_Database._counter--;
		if(db_Database._counter == 0) {
			Manager.jWindow().trigger("loadDB");
		}
	},where);
};
var db_Members = function() { };
db_Members.__name__ = true;
db_Members.load = function() {
	db_Database.load(db_Members.db = [],"members",db_Members.COLUMN_LIST);
};
var db_Tasks = function() { };
db_Tasks.__name__ = true;
db_Tasks.load = function(pastDate) {
	if(pastDate == null) {
		pastDate = "1999-1-1";
	}
	db_Database.load(db_Tasks.db = [],"tasks",db_Tasks.COLUMN_LIST,"updatetime > \"" + pastDate + "\"");
};
var db_Works = function() { };
db_Works.__name__ = true;
db_Works.load = function() {
	db_Database.load(db_Works.db = [],"works",db_Works.COLUMN_LIST);
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
var haxe_Http = function(url) {
	this.url = url;
	this.headers = new List();
	this.params = new List();
	this.async = true;
	this.withCredentials = false;
};
haxe_Http.__name__ = true;
haxe_Http.prototype = {
	setParameter: function(param,value) {
		this.params = Lambda.filter(this.params,function(p) {
			return p.param != param;
		});
		this.params.push({ param : param, value : value});
		return this;
	}
	,request: function(post) {
		var me = this;
		me.responseData = null;
		var r = this.req = js_Browser.createXMLHttpRequest();
		var onreadystatechange = function(_) {
			if(r.readyState != 4) {
				return;
			}
			var s;
			try {
				s = r.status;
			} catch( e ) {
				s = null;
			}
			if(s != null && "undefined" !== typeof window) {
				var protocol = window.location.protocol.toLowerCase();
				var rlocalProtocol = new EReg("^(?:about|app|app-storage|.+-extension|file|res|widget):$","");
				var isLocal = rlocalProtocol.match(protocol);
				if(isLocal) {
					if(r.responseText != null) {
						s = 200;
					} else {
						s = 404;
					}
				}
			}
			if(s == undefined) {
				s = null;
			}
			if(s != null) {
				me.onStatus(s);
			}
			if(s != null && s >= 200 && s < 400) {
				me.req = null;
				me.onData(me.responseData = r.responseText);
			} else if(s == null) {
				me.req = null;
				me.onError("Failed to connect or resolve host");
			} else {
				switch(s) {
				case 12007:
					me.req = null;
					me.onError("Unknown host");
					break;
				case 12029:
					me.req = null;
					me.onError("Failed to connect to host");
					break;
				default:
					me.req = null;
					me.responseData = r.responseText;
					me.onError("Http Error #" + r.status);
				}
			}
		};
		if(this.async) {
			r.onreadystatechange = onreadystatechange;
		}
		var uri = this.postData;
		if(uri != null) {
			post = true;
		} else {
			var _g_head = this.params.h;
			while(_g_head != null) {
				var val = _g_head.item;
				_g_head = _g_head.next;
				var p = val;
				if(uri == null) {
					uri = "";
				} else {
					uri += "&";
				}
				var s1 = p.param;
				var uri1 = encodeURIComponent(s1) + "=";
				var s2 = p.value;
				uri += uri1 + encodeURIComponent(s2);
			}
		}
		try {
			if(post) {
				r.open("POST",this.url,this.async);
			} else if(uri != null) {
				var question = this.url.split("?").length <= 1;
				r.open("GET",this.url + (question ? "?" : "&") + uri,this.async);
				uri = null;
			} else {
				r.open("GET",this.url,this.async);
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			me.req = null;
			this.onError(e1.toString());
			return;
		}
		r.withCredentials = this.withCredentials;
		if(!Lambda.exists(this.headers,function(h) {
			return h.header == "Content-Type";
		}) && post && this.postData == null) {
			r.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
		}
		var _g_head1 = this.headers.h;
		while(_g_head1 != null) {
			var val1 = _g_head1.item;
			_g_head1 = _g_head1.next;
			var h1 = val1;
			r.setRequestHeader(h1.header,h1.value);
		}
		r.send(uri);
		if(!this.async) {
			onreadystatechange(null);
		}
	}
	,onData: function(data) {
	}
	,onError: function(msg) {
	}
	,onStatus: function(status) {
	}
};
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ds_IntMap = function() {
	this.h = { };
};
haxe_ds_IntMap.__name__ = true;
haxe_ds_IntMap.__interfaces__ = [haxe_IMap];
haxe_ds_IntMap.prototype = {
	keys: function() {
		var a = [];
		for( var key in this.h ) if(this.h.hasOwnProperty(key)) {
			a.push(key | 0);
		}
		return HxOverrides.iter(a);
	}
};
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
};
var jp_saken_common_utils_API = function() { };
jp_saken_common_utils_API.__name__ = true;
jp_saken_common_utils_API.init = function(path) {
	jp_saken_common_utils_API._path = path;
};
jp_saken_common_utils_API.getJSON = function(name,params,onLoaded) {
	jp_saken_common_utils_API.getString(name,params,function(data) {
		var tmp = JSON.parse(data);
		onLoaded(tmp);
	});
};
jp_saken_common_utils_API.getString = function(name,params,onLoaded) {
	var http = new haxe_Http(jp_saken_common_utils_API._path + name + "/");
	http.onData = function(data) {
		if(onLoaded != null) {
			onLoaded(data);
		}
	};
	if(params != null) {
		var key = params.keys();
		while(key.hasNext()) {
			var key1 = key.next();
			http.setParameter(key1,__map_reserved[key1] != null ? params.getReserved(key1) : params.h[key1]);
		}
	}
	http.request(true);
};
jp_saken_common_utils_API.getIP = function(onLoaded) {
	var _g = new haxe_ds_StringMap();
	if(__map_reserved["key"] != null) {
		_g.setReserved("key","ip");
	} else {
		_g.h["key"] = "ip";
	}
	jp_saken_common_utils_API.getString("handy",_g,onLoaded);
};
var jp_saken_common_utils_Handy = function() { };
jp_saken_common_utils_Handy.__name__ = true;
jp_saken_common_utils_Handy.getPastDate = function(date,num) {
	if(num == null) {
		num = 30;
	}
	var second = HxOverrides.strDate(date).getTime() - num * 86400000;
	var date1 = new Date(second);
	var m = jp_saken_common_utils_Handy.getFilledNumber(date1.getMonth() + 1,2);
	var d = jp_saken_common_utils_Handy.getFilledNumber(date1.getDate(),2);
	return date1.getFullYear() + "-" + m + "-" + d;
};
jp_saken_common_utils_Handy.getPastMonth = function(date,num) {
	if(num == null) {
		num = 1;
	}
	var y = date.getFullYear();
	var m = date.getMonth() + 1;
	m -= num;
	if(m < 1) {
		m += 12;
		--y;
	}
	return y + "-" + jp_saken_common_utils_Handy.getFilledNumber(m,2);
};
jp_saken_common_utils_Handy.getFilledNumber = function(num,digits) {
	if(digits == null) {
		digits = 3;
	}
	var result = num + "";
	var blankLength = digits - jp_saken_common_utils_Handy.getDigits(num);
	var _g1 = 0;
	var _g = blankLength;
	while(_g1 < _g) {
		var i = _g1++;
		result = "0" + result;
	}
	return result;
};
jp_saken_common_utils_Handy.getDigits = function(val) {
	return (val + "").length;
};
jp_saken_common_utils_Handy.getFormattedPrice = function(price) {
	var string = price == null ? "null" : "" + price;
	var length = string.length;
	var result = "";
	var _g1 = 0;
	var _g = length;
	while(_g1 < _g) {
		var i = _g1++;
		if(i > 0 && (length - i) % 3 == 0) {
			result += ",";
		}
		result += string.charAt(i);
	}
	return "￥" + result + "-";
};
jp_saken_common_utils_Handy.getLinkedHTML = function(text,target) {
	if(target == null) {
		target = "_blank";
	}
	if(new EReg("http","").match(text)) {
		var _this_r = new RegExp("((http|https)://[0-9a-z-/._?=&%\\[\\]~^:]+)","gi".split("u").join(""));
		text = text.replace(_this_r,"<a href=\"$1\" target=\"" + target + "\">$1</a>");
	}
	return text;
};
jp_saken_common_utils_Handy.getBreakedHTML = function(text) {
	if(new EReg("\n","").match(text)) {
		var _this_r = new RegExp("\r?\n","g".split("u").join(""));
		text = text.replace(_this_r,"<br>");
	}
	return text;
};
jp_saken_common_utils_Handy.getAdjustedHTML = function(text) {
	return jp_saken_common_utils_Handy.getLinkedHTML(jp_saken_common_utils_Handy.getBreakedHTML(text));
};
jp_saken_common_utils_Handy.getLines = function(text) {
	return jp_saken_common_utils_Handy.getNumberOfCharacter(text,"\n") + 1;
};
jp_saken_common_utils_Handy.getNumberOfCharacter = function(text,character) {
	return text.split(character).length - 1;
};
jp_saken_common_utils_Handy.getLimitedText = function(text,count) {
	if(count == null) {
		count = 10;
	}
	if(text.length > count) {
		text = HxOverrides.substr(text,0,count) + "...";
	}
	return text;
};
jp_saken_common_utils_Handy.getReplacedSC = function(text) {
	text = StringTools.replace(text,"'","&#039;");
	text = StringTools.replace(text,"\\","&#47;");
	return text;
};
jp_saken_common_utils_Handy.getSlicedArray = function(array,num) {
	if(num == null) {
		num = 1000;
	}
	var results = [];
	var _g1 = 0;
	var _g = Math.ceil(array.length / num);
	while(_g1 < _g) {
		var i = _g1++;
		var j = i * num;
		results.push(array.slice(j,j + num));
	}
	return results;
};
jp_saken_common_utils_Handy.shuffleArray = function(array) {
	var copy = array.slice();
	var results = [];
	var length = copy.length;
	var _g1 = 0;
	var _g = length;
	while(_g1 < _g) {
		var i = _g1++;
		var index = Math.floor(Math.random() * length);
		results.push(copy[index]);
		copy.splice(index,1);
	}
	return results;
};
jp_saken_common_utils_Handy.getMap = function(array) {
	var map = new haxe_ds_IntMap();
	var _g1 = 0;
	var _g = array.length;
	while(_g1 < _g) {
		var i = _g1++;
		var info = array[i];
		var id = info.id;
		Reflect.deleteField(info,"id");
		var fields = Reflect.fields(info);
		var value = fields.length > 1 ? info : Reflect.getProperty(info,fields[0]);
		var v = value;
		map.h[id] = v;
	}
	return map;
};
jp_saken_common_utils_Handy.getLength = function(map) {
	if(map == null) {
		return 0;
	}
	var result = 0;
	var key = map.keys();
	while(key.hasNext()) {
		var key1 = key.next();
		++result;
	}
	return result;
};
jp_saken_common_utils_Handy.isImageSource = function(value) {
	return new EReg("data:image","").match(value);
};
jp_saken_common_utils_Handy.isMailaddress = function(value) {
	return new EReg("^([a-zA-Z0-9])+([a-zA-Z0-9\\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\\._-]+)+$","").match(value);
};
jp_saken_common_utils_Handy.timer = function(func,time) {
	if(time == null) {
		time = 1000;
	}
	var timer = new haxe_Timer(time);
	timer.run = function() {
		timer.stop();
		func();
	};
};
jp_saken_common_utils_Handy.prototype = {
	getRoundNumber: function(val,digits) {
		var m = Math.pow(10,digits);
		var d = Math.pow(.1,digits);
		return Math.floor(val * m) * d;
	}
};
var jp_saken_js_components_Lightbox = function() { };
jp_saken_js_components_Lightbox.__name__ = true;
jp_saken_js_components_Lightbox.init = function(cls,jField) {
	jp_saken_js_components_Lightbox._jWindow = $(window);
	jp_saken_js_components_Lightbox._jBody = $("body");
	jp_saken_js_components_Lightbox.setHTML();
	jp_saken_js_components_Lightbox._jParent = $("#" + "lightbox");
	jp_saken_js_components_Lightbox._jBackground = jp_saken_js_components_Lightbox._jParent.find(".bg").css({ opacity : .8});
	jp_saken_js_components_Lightbox._jContent = jp_saken_js_components_Lightbox._jParent.find(".content");
	jp_saken_js_components_Lightbox._class = cls;
	if(jField == null) {
		jField = jp_saken_js_components_Lightbox._jBody;
	}
	jp_saken_js_components_Lightbox._jBackground.add(jp_saken_js_components_Lightbox._jParent.find(".close")).on("click",null,jp_saken_js_components_Lightbox.hide);
	jp_saken_js_components_Lightbox._jWindow.on("resize",null,jp_saken_js_components_Lightbox.resize);
	jField.on("click",null,jp_saken_js_components_Lightbox.onClick);
};
jp_saken_js_components_Lightbox.setHTML = function() {
	var html = "\n\t\t<section id=\"" + "lightbox" + "\">\n\t\t\t<div class=\"bg\" id=\"" + "lightbox" + "-bg\">&nbsp;</div>\n\t\t\t<section class=\"content\" id=\"" + "lightbox" + "-content\"></section>\n\t\t\t<button class=\"close\" id=\"" + "lightbox" + "-close\">×</button>\n\t\t</section>";
	jp_saken_js_components_Lightbox._jBody.append(html);
};
jp_saken_js_components_Lightbox.onClick = function(event) {
	var jTarget = $(event.target);
	var jAnchor = jTarget.parents(jp_saken_js_components_Lightbox._class);
	if(jAnchor.length == 0) {
		return;
	}
	var href = jAnchor.prop("href");
	if(href.length > 0) {
		event.preventDefault();
		jp_saken_js_components_Lightbox.show(href);
	}
};
jp_saken_js_components_Lightbox.show = function(src) {
	jp_saken_js_components_Lightbox._jContent.empty().css({ width : "", height : ""}).html("<img src=\"" + src + "\">").find("img").on("load",null,jp_saken_js_components_Lightbox.resize);
	jp_saken_js_components_Lightbox._jParent.stop().fadeIn(300);
};
jp_saken_js_components_Lightbox.hide = function(event) {
	jp_saken_js_components_Lightbox._jParent.stop().fadeOut(300);
};
jp_saken_js_components_Lightbox.resize = function(event) {
	var jTarget = jp_saken_js_components_Lightbox._jContent.find("img");
	var winW = jp_saken_js_components_Lightbox._jWindow.width();
	var winH = jp_saken_js_components_Lightbox._jWindow.height();
	var w = jTarget.width();
	var h = jTarget.height();
	if(w > winW) {
		w = winW;
	}
	if(h > winH) {
		h = winH;
	}
	var x = Math.floor((winW - w) * .5);
	var y = Math.floor((winH - h) * .5);
	jp_saken_js_components_Lightbox._jContent.css({ left : x, top : y, width : w, height : h});
};
var jp_saken_js_ui_UI = function() { };
jp_saken_js_ui_UI.__name__ = true;
jp_saken_js_ui_UI.setPagetop = function(jTrigger,speed,easing) {
	if(easing == null) {
		easing = "easeOutSine";
	}
	if(speed == null) {
		speed = 200;
	}
	jp_saken_js_ui_UI.setAnchor(jTrigger,speed,easing);
};
jp_saken_js_ui_UI.setAnchor = function(jTrigger,speed,easing,jFix) {
	if(easing == null) {
		easing = "easeOutSine";
	}
	if(speed == null) {
		speed = 200;
	}
	var jHtml = $("html,body");
	jTrigger.on("click",null,function(event) {
		var href = jp_saken_js_ui_UI.getHref($(event.currentTarget),"anchor");
		if(href == null) {
			return;
		}
		var jGoal = $(href);
		if(jGoal.length == 0) {
			return;
		}
		var top = jGoal.offset().top;
		if(jFix != null) {
			top -= jFix.outerHeight() + 10;
		}
		event.preventDefault();
		jHtml.stop().animate({ scrollTop : top},speed,easing);
	});
};
jp_saken_js_ui_UI.setImageHover = function(jList) {
	var jBody = $("body");
	var set = function(jAnchor) {
		var href = jAnchor.prop("href");
		if(href == null || href.length == 0) {
			return;
		}
		var jImage = jAnchor.find("img");
		if(jImage.length == 0) {
			return;
		}
		var defaultSrc = jImage.prop("src");
		var changedSrc = StringTools.replace(defaultSrc,"_off","_on");
		if(defaultSrc == changedSrc) {
			return;
		}
		jAnchor.on({ mouseover : function(event) {
			if(jBody.hasClass("sp")) {
				return;
			}
			jImage.prop("src",changedSrc);
		}, mouseout : function(event1) {
			if(jAnchor.hasClass("current")) {
				return;
			}
			jImage.prop("src",defaultSrc);
		}, forcedtochange : function(event2) {
			jImage.prop("src",changedSrc);
		}});
	};
	var _g1 = 0;
	var _g = jList.length;
	while(_g1 < _g) {
		var i = _g1++;
		set(jList.eq(i));
	}
};
jp_saken_js_ui_UI.setAccordion = function(jTriggers,speed) {
	if(speed == null) {
		speed = 200;
	}
	var open = function(jTrigger,jContent) {
		jTrigger.addClass("opened");
		jContent.stop().slideDown(speed);
	};
	var close = function(jTrigger1,jContent1) {
		jTrigger1.removeClass("opened");
		jContent1.stop().slideUp(speed);
	};
	jTriggers.on("click",null,function(event) {
		var jTrigger2 = $(event.currentTarget);
		var href = jp_saken_js_ui_UI.getHref(jTrigger2,"accordion");
		if(href == null) {
			return;
		}
		var jContent2 = $(href);
		if(jContent2.length == 0) {
			return;
		}
		event.preventDefault();
		if(jTrigger2.hasClass("opened")) {
			close(jTrigger2,jContent2);
		} else {
			open(jTrigger2,jContent2);
		}
	});
};
jp_saken_js_ui_UI.setTab = function(jParents) {
	var init = function(jParent) {
		var jTriggers = jParent.find(".tabTrigger");
		var jContents = jParent.find(".tabContent");
		jTriggers.on("click",null,function(event) {
			var jTrigger = $(event.currentTarget);
			var key = jTrigger.data("tab");
			var jContent = jContents.filter("[data-tab=\"" + key + "\"]");
			jTriggers.add(jContents).removeClass("active");
			jTrigger.add(jContent).addClass("active");
		}).eq(0).trigger("click");
	};
	var _g1 = 0;
	var _g = jParents.length;
	while(_g1 < _g) {
		var i = _g1++;
		init(jParents.eq(i));
	}
};
jp_saken_js_ui_UI.setTextSelector = function(jTrigger,jTarget) {
	jTrigger.on("click",null,function(event) {
		var range = window.document.createRange();
		var element = jTarget.get(0);
		var selection = window.getSelection();
		range.selectNodeContents(element);
		selection.removeAllRanges();
		selection.addRange(range);
	});
};
jp_saken_js_ui_UI.getHref = function(jTarget,key) {
	var result = jTarget.data(key);
	if(result == null) {
		result = "#" + jTarget.prop("href").split("#")[1];
	}
	if(result.indexOf("#") < 0) {
		result = null;
	}
	return result;
};
var jp_saken_js_utils_Ajax = function() { };
jp_saken_js_utils_Ajax.__name__ = true;
jp_saken_js_utils_Ajax.getIP = function(onLoaded) {
	var http = new haxe_Http("files/php/" + "getIP.php");
	jp_saken_js_utils_Ajax.setBusy();
	http.onData = function(data) {
		onLoaded(data);
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	http.request(true);
};
jp_saken_js_utils_Ajax.getDatetime = function(onLoaded) {
	var http = new haxe_Http("files/php/" + "getDatetime.php");
	jp_saken_js_utils_Ajax.setBusy();
	http.onData = function(data) {
		var tmp = JSON.parse(data);
		onLoaded(tmp);
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	http.request(true);
};
jp_saken_js_utils_Ajax.uploadImage = function(filename,base64,onLoaded) {
	var http = new haxe_Http("files/php/" + "uploadImage.php");
	jp_saken_js_utils_Ajax.setBusy();
	http.onData = function(data) {
		if(onLoaded != null) {
			onLoaded();
		}
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	http.setParameter("filename",filename);
	http.setParameter("base64",base64);
	http.request(true);
};
jp_saken_js_utils_Ajax.deleteImage = function(filename,onLoaded) {
	var http = new haxe_Http("files/php/" + "deleteImage.php");
	jp_saken_js_utils_Ajax.setBusy();
	http.onData = function(data) {
		if(onLoaded != null) {
			onLoaded();
		}
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	http.setParameter("filename",filename);
	http.request(true);
};
jp_saken_js_utils_Ajax.getData = function(table,columns,onLoaded,where) {
	if(where == null) {
		where = "";
	}
	jp_saken_js_utils_Ajax.setConnectDB();
	jp_saken_js_utils_Ajax._connectDB.onData = function(data) {
		var tmp = JSON.parse(data);
		onLoaded(tmp);
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	var query = "SELECT " + columns.join(",") + " FROM " + table;
	if(where.length > 0) {
		query += " WHERE " + where;
	}
	jp_saken_js_utils_Ajax.requestConnectDB(query);
};
jp_saken_js_utils_Ajax.getMaxData = function(table,column,onLoaded,where) {
	if(where == null) {
		where = "";
	}
	jp_saken_js_utils_Ajax.setConnectDB();
	jp_saken_js_utils_Ajax._connectDB.onData = function(data) {
		var reg = new EReg("([0-9]+)","");
		var isMatch = reg.match(data);
		var tmp = isMatch ? Std.parseInt(reg.matched(0)) : 0;
		onLoaded(tmp);
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	var query = "SELECT MAX(" + column + ") FROM " + table;
	if(where.length > 0) {
		query += " WHERE " + where;
	}
	jp_saken_js_utils_Ajax.requestConnectDB(query);
};
jp_saken_js_utils_Ajax.getIsEmpty = function(table,onLoaded,where) {
	jp_saken_js_utils_Ajax.getData(table,["id"],function(data) {
		onLoaded(data.length < 1);
	},where);
};
jp_saken_js_utils_Ajax.insertData = function(table,columns,values,onLoaded) {
	jp_saken_js_utils_Ajax.setConnectDB();
	jp_saken_js_utils_Ajax._connectDB.onData = function(data) {
		if(onLoaded != null) {
			onLoaded(Std.parseInt(data));
		}
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	var _g1 = 0;
	var _g = values.length;
	while(_g1 < _g) {
		var i = _g1++;
		values[i] = "'" + Std.string(values[i]) + "'";
	}
	var query = "INSERT INTO " + table + " (" + columns.join(",") + ") VALUES (" + values.join(",") + ")";
	jp_saken_js_utils_Ajax.requestConnectDB(query,true);
};
jp_saken_js_utils_Ajax.updateData = function(table,columns,values,where,onLoaded) {
	jp_saken_js_utils_Ajax.setConnectDB();
	jp_saken_js_utils_Ajax._connectDB.onData = function(data) {
		if(onLoaded != null) {
			onLoaded();
		}
		jp_saken_js_utils_Ajax.unsetBusy();
	};
	var array = [];
	var _g1 = 0;
	var _g = columns.length;
	while(_g1 < _g) {
		var p = _g1++;
		array[p] = columns[p] + "= '" + Std.string(values[p]) + "'";
	}
	var query = "UPDATE " + table + " SET " + array.join(",") + " WHERE " + where;
	jp_saken_js_utils_Ajax.requestConnectDB(query);
};
jp_saken_js_utils_Ajax.setConnectDB = function() {
	jp_saken_js_utils_Ajax._connectDB = new haxe_Http("files/php/" + "connectDB.php");
};
jp_saken_js_utils_Ajax.requestConnectDB = function(query,isInsert) {
	if(isInsert == null) {
		isInsert = false;
	}
	jp_saken_js_utils_Ajax.setBusy();
	jp_saken_js_utils_Ajax._connectDB.setParameter("query",query);
	if(isInsert) {
		jp_saken_js_utils_Ajax._connectDB.setParameter("insert","true");
	}
	jp_saken_js_utils_Ajax._connectDB.request(true);
};
jp_saken_js_utils_Ajax.setBusy = function() {
	$(window).on("beforeunload",null,jp_saken_js_utils_Ajax.onBeforeunload);
};
jp_saken_js_utils_Ajax.unsetBusy = function() {
	$(window).unbind("beforeunload",jp_saken_js_utils_Ajax.onBeforeunload);
};
jp_saken_js_utils_Ajax.onBeforeunload = function(event) {
	return "データベース登録中です。";
};
var jp_saken_js_utils_Handy = function() { };
jp_saken_js_utils_Handy.__name__ = true;
jp_saken_js_utils_Handy.getUA = function() {
	return jp_saken_js_utils_Handy._window.navigator.userAgent;
};
jp_saken_js_utils_Handy.alert = function(value) {
	jp_saken_js_utils_Handy._window.alert(value);
};
jp_saken_js_utils_Handy.confirm = function(text,ok,cancel) {
	if(jp_saken_js_utils_Handy._window.confirm(text)) {
		ok();
	} else if(cancel != null) {
		cancel();
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_Browser = function() { };
js_Browser.__name__ = true;
js_Browser.createXMLHttpRequest = function() {
	if(typeof XMLHttpRequest != "undefined") {
		return new XMLHttpRequest();
	}
	if(typeof ActiveXObject != "undefined") {
		return new ActiveXObject("Microsoft.XMLHTTP");
	}
	throw new js__$Boot_HaxeError("Unable to create XMLHttpRequest object.");
};
var js_Cookie = function() { };
js_Cookie.__name__ = true;
js_Cookie.set = function(name,value,expireDelay,path,domain) {
	var s = name + "=" + encodeURIComponent(value);
	if(expireDelay != null) {
		var t = new Date().getTime() + expireDelay * 1000;
		var d = new Date(t);
		s += ";expires=" + d.toGMTString();
	}
	if(path != null) {
		s += ";path=" + path;
	}
	if(domain != null) {
		s += ";domain=" + domain;
	}
	window.document.cookie = s;
};
js_Cookie.all = function() {
	var h = new haxe_ds_StringMap();
	var a = window.document.cookie.split(";");
	var _g = 0;
	while(_g < a.length) {
		var e = a[_g];
		++_g;
		e = StringTools.ltrim(e);
		var t = e.split("=");
		if(t.length < 2) {
			continue;
		}
		var key = t[0];
		var value = decodeURIComponent(t[1].split("+").join(" "));
		if(__map_reserved[key] != null) {
			h.setReserved(key,value);
		} else {
			h.h[key] = value;
		}
	}
	return h;
};
js_Cookie.get = function(name) {
	var _this = js_Cookie.all();
	if(__map_reserved[name] != null) {
		return _this.getReserved(name);
	} else {
		return _this.h[name];
	}
};
js_Cookie.remove = function(name,path,domain) {
	js_Cookie.set(name,"",-10,path,domain);
};
var ui_Datalist = function() { };
ui_Datalist.__name__ = true;
ui_Datalist.set = function(jTarget,mode,clientID) {
	var _g = new haxe_ds_StringMap();
	if(__map_reserved["mode"] != null) {
		_g.setReserved("mode",mode);
	} else {
		_g.h["mode"] = mode;
	}
	var param = _g;
	if(clientID != null) {
		if(__map_reserved["clientID"] != null) {
			param.setReserved("clientID",clientID);
		} else {
			param.h["clientID"] = clientID;
		}
	}
	jp_saken_common_utils_API.getJSON("dailyReport2",param,function(data) {
		var html = "";
		var _g2 = 0;
		var _g1 = data.length;
		while(_g2 < _g1) {
			var i = _g2++;
			var info = data[i];
			html += "<option value=\"" + Std.string(info.name) + "\" data-id=\"" + Std.string(info.id) + "\"></option>";
		}
		jTarget.html(html);
	});
};
var ui_Keyboard = function() { };
ui_Keyboard.__name__ = true;
ui_Keyboard.init = function() {
	Manager.jWindow().on("keydown",null,ui_Keyboard.onKeydown);
};
ui_Keyboard.onKeydown = function(event) {
	var jTarget = $(event.target);
	var keyCode = event.keyCode;
	if(event.ctrlKey) {
		switch(keyCode) {
		case 65:case 68:
			view_ReportViewer.archiveAll();
			event.preventDefault();
			break;
		case 76:
			Manager.logout();
			break;
		default:
		}
	}
};
var utils_Data = function() { };
utils_Data.__name__ = true;
utils_Data.getDate = function(datetime) {
	var date = datetime.split(" ")[0];
	var _this_r = new RegExp("-","g".split("u").join(""));
	date = date.replace(_this_r,".");
	return date;
};
utils_Data.getDay = function(datetime) {
	return utils_Data.DAY_LIST[HxOverrides.strDate(datetime).getDay()] + ".";
};
var utils_TimeKeeper = function() { };
utils_TimeKeeper.__name__ = true;
utils_TimeKeeper.run = function() {
	utils_TimeKeeper._timer = new haxe_Timer(3000);
	utils_TimeKeeper._timer.run = utils_TimeKeeper.onLoop;
};
utils_TimeKeeper.stop = function() {
	utils_TimeKeeper._timer.stop();
};
utils_TimeKeeper.onLoop = function() {
	view_SimpleBoard.onLoop();
	view_Information.onLoop();
	view_StarChecker.onLoop();
	view_ReportViewer.onLoop();
	view_reportviewer_AutoSave.onLoop();
};
var view_Information = function() { };
view_Information.__name__ = true;
view_Information.init = function() {
	view_Information._jParent = $("#information");
	view_Information._jLength = view_Information._jParent.find(".length");
	$("h1").add(view_Information._jParent).on("click",null,view_Information.onClick);
};
view_Information.run = function() {
	view_Information._lastDatetime = Manager.visitDatetime;
};
view_Information.onLoop = function() {
	view_Information.getData(["id","updatetime"],view_Information.set);
};
view_Information.getData = function(columns,onLoaded) {
	var where = "updatetime > \"" + view_Information._lastDatetime + "\" AND member_id != " + Manager.myID;
	jp_saken_js_utils_Ajax.getData("reports",columns,onLoaded,where);
};
view_Information.set = function(data) {
	var length = data.length;
	if(length == 0) {
		return;
	}
	view_Information._jLength.text(length == null ? "null" : "" + length);
	view_Information._jParent.stop().fadeIn(300);
};
view_Information.onClick = function(event) {
	Manager.reload();
	view_Information._jLength.text("0");
	view_Information._jParent.stop().fadeOut(300);
	jp_saken_js_utils_Ajax.getDatetime(function(datetime) {
		view_Information._lastDatetime = datetime;
	});
};
var view_Login = function() { };
view_Login.__name__ = true;
view_Login.init = function() {
	view_Login._jParent = $("#login");
	view_Login._jID = view_Login._jParent.find(".id");
	view_Login._jPass = view_Login._jParent.find(".pass");
	view_Login._jSubmit = view_Login._jParent.find(".submit").on("click",null,view_Login.submit);
};
view_Login.show = function() {
	js_Cookie.remove("DR2LoginHistory2");
	view_Login._jID.add(view_Login._jPass).prop("value","");
	view_Login._jParent.fadeIn(300,function() {
		view_Login._jID.trigger("focus");
	});
};
view_Login.hide = function() {
	view_Login._jParent.stop().hide();
};
view_Login.start = function() {
	view_Login._jID.trigger("focus");
	var cookie = js_Cookie.get("DR2LoginHistory2");
	if(cookie == null) {
		return;
	}
	var info = JSON.parse(cookie);
	view_Login._jID.prop("value",info[0]);
	view_Login._jPass.prop("value",info[1]);
	view_Login.submit();
};
view_Login.submit = function(event) {
	var id = view_Login._jID.prop("value");
	var pass = view_Login._jPass.prop("value");
	var table = "members";
	var columns = ["*"];
	var _this_r = new RegExp("_","".split("u").join(""));
	id = id.replace(_this_r,"-");
	var where = "(parmanent_number = \"" + id + "\" OR parmanent_id = \"" + id + "\") AND pass = \"" + pass + "\"";
	jp_saken_js_utils_Ajax.getData(table,columns,view_Login.checkData,where);
	if(event != null) {
		event.preventDefault();
	}
};
view_Login.checkData = function(data) {
	if(data.length == 0) {
		jp_saken_js_utils_Handy.alert("登録されていないアカウントです。");
		return;
	}
	var info = data[0];
	var cookie = JSON.stringify([info.parmanent_number,info.pass]);
	js_Cookie.set("DR2LoginHistory2",cookie);
	Manager.myID = info.id;
	Manager.myParmanentID = info.parmanent_id;
	Manager.myName = info.name;
	Manager.myTeam = info.team;
	Manager.login();
};
var view_ReportViewer = function() { };
view_ReportViewer.__name__ = true;
view_ReportViewer.init = function() {
	view_ReportViewer._jParent = $("#reportviewer");
	view_ReportViewer._jContents = view_ReportViewer._jParent.find("#reportviewer-content").on({ click : view_ReportViewer.onClick, keydown : view_ReportViewer.onKeyup, change : view_ReportViewer.onChange});
	view_ReportViewer._jClientDatalist = view_ReportViewer._jParent.find("#client-datalist");
	view_ReportViewer._jWorkDatalist = view_ReportViewer._jParent.find("#work-datalist");
	view_reportviewer_AutoSave.init(view_ReportViewer._jContents);
	view_reportviewer_SortNavi.init(view_ReportViewer._jParent.find("#sort-navi"));
	view_reportviewer_SearchNavi.init(view_ReportViewer._jParent.find("#search-navi"));
	jp_saken_js_components_Lightbox.init(".lightbox");
	view_reportviewer_Scrollbar.init(view_ReportViewer._jParent);
	ui_Datalist.set(view_ReportViewer._jClientDatalist,"clients");
};
view_ReportViewer.show = function() {
	view_ReportViewer.loadDB(function() {
		view_ReportViewer._jParent.show();
		view_reportviewer_SortNavi.showNew();
	});
};
view_ReportViewer.hide = function() {
	view_ReportViewer.reset();
	view_ReportViewer._jParent.stop().hide();
};
view_ReportViewer.loadDB = function(onLoaded) {
	jp_saken_js_utils_Ajax.getData("reports",["*"],function(data) {
		view_ReportViewer._fullData = view_ReportViewer.getSortedFullData(data);
		if(onLoaded != null) {
			onLoaded();
		}
	},"date > \"" + Manager.pastDate + "\"");
};
view_ReportViewer.showReports = function(category,eReg) {
	view_ReportViewer._jContents.removeClass().addClass(category).empty();
	view_ReportViewer._currentData = view_ReportViewer.getChoicedData(category,eReg);
	view_ReportViewer._current = 0;
	if(category == "new") {
		view_ReportViewer.addNewEditor(Manager.myID,Manager.visitDate);
	}
	view_ReportViewer.loadMore();
};
view_ReportViewer.loadMore = function(length) {
	if(length == null) {
		length = 10;
	}
	view_ReportViewer._jContents.append(view_ReportViewer.getHTML(view_ReportViewer._currentData,length));
	view_ReportViewer.fadein();
};
view_ReportViewer.archiveAll = function() {
	var jList = view_ReportViewer._jContents.find(".report").not(".archived");
	var _g1 = 0;
	var _g = jList.length;
	while(_g1 < _g) {
		var p = _g1++;
		var jTarget = jList.eq(p);
		if(jTarget.data("id") != 0) {
			view_ReportViewer.archiveReport(jTarget,false);
		}
	}
	view_ReportViewer.loadMore();
};
view_ReportViewer.search = function(value) {
	view_ReportViewer.showReports("searching",new EReg(value,"i"));
};
view_ReportViewer.reset = function() {
	view_reportviewer_SearchNavi.input("");
	view_reportviewer_SortNavi.clear();
	view_ReportViewer._jContents.empty();
};
view_ReportViewer.setTotaltime = function(jReport) {
	var totaltime = 0;
	var jTasks = jReport.find(".tasks").find(".task");
	var _g1 = 0;
	var _g = jTasks.length;
	while(_g1 < _g) {
		var i = _g1++;
		var value = jTasks.eq(i).find(".hour").find("input").prop("value");
		if(value.length == 0) {
			value = "0";
		}
		totaltime += parseFloat(value);
	}
	totaltime = Math.ceil(totaltime * 10) / 10;
	jReport.find(".totaltime").find("span").text(totaltime == null ? "null" : "" + totaltime);
};
view_ReportViewer.updateStars = function(reportID,stars) {
	var _g1 = 0;
	var _g = view_ReportViewer._fullData.length;
	while(_g1 < _g) {
		var p = _g1++;
		if(view_ReportViewer._fullData[p].id == reportID) {
			view_ReportViewer._fullData[p].star_list = stars;
		}
	}
};
view_ReportViewer.onLoop = function() {
	var jTask = view_ReportViewer._jContents.find(".task");
	var jFocus = jTask.find(":focus").parents(".task");
	if(jFocus.hasClass("lastFocus")) {
		return;
	}
	jTask.removeClass("lastFocus");
	jFocus.addClass("lastFocus");
	view_ReportViewer.setWorkDatalist(jFocus);
};
view_ReportViewer.getSortedFullData = function(data) {
	var dates = [];
	var dataOfDate = new haxe_ds_StringMap();
	data.reverse();
	var _g1 = 0;
	var _g = data.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info = data[p];
		var date = info.date;
		var array = __map_reserved[date] != null ? dataOfDate.getReserved(date) : dataOfDate.h[date];
		if(array == null) {
			array = [];
			dates.push(date);
		}
		array.push(info);
		if(__map_reserved[date] != null) {
			dataOfDate.setReserved(date,array);
		} else {
			dataOfDate.h[date] = array;
		}
	}
	dates.sort(function(a,b) {
		return Math.floor(HxOverrides.strDate(b).getTime() - HxOverrides.strDate(a).getTime());
	});
	data = [];
	var _g11 = 0;
	var _g2 = dates.length;
	while(_g11 < _g2) {
		var p1 = _g11++;
		var date1 = dates[p1];
		var array1 = __map_reserved[date1] != null ? dataOfDate.getReserved(date1) : dataOfDate.h[date1];
		array1.sort(function(a1,b1) {
			if(a1.updatetime < b1.updatetime) {
				return 1;
			} else {
				return -1;
			}
		});
		data = data.concat(array1);
	}
	return data;
};
view_ReportViewer.getChoicedData = function(category,eReg) {
	if(category == "all") {
		return view_ReportViewer._fullData;
	}
	var myID = Manager.myID;
	var team = category.split(" ")[0];
	var getChoiceNew = function(info) {
		return info.archived_list.split(",").indexOf(myID) == -1;
	};
	var getChoiceStared = function(info1) {
		return info1.star_list.split(",").indexOf(myID) > -1;
	};
	var getChoiceSelf = function(info2) {
		return info2.member_id == myID;
	};
	var getChoiceTeam = function(info3) {
		var memberDB = db_Members.db[info3.member_id];
		var value = memberDB.team;
		if(value.length == 0) {
			value = memberDB.section;
		}
		return value == team;
	};
	var getChoiceSearch = function(info4) {
		var getChoiceSearch1 = view_ReportViewer.getReportString(info4);
		return eReg.match(getChoiceSearch1);
	};
	var data = [];
	var getIsMatch = category == "new" ? getChoiceNew : category == "searching" ? getChoiceSearch : category == "stared" ? getChoiceStared : category == "self" ? getChoiceSelf : getChoiceTeam;
	var _g1 = 0;
	var _g = view_ReportViewer._fullData.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info5 = view_ReportViewer._fullData[p];
		if(getIsMatch(info5)) {
			data.push(info5);
		}
	}
	return data;
};
view_ReportViewer.getHTML = function(data,length) {
	var html = "";
	var a = view_ReportViewer._current;
	var b = view_ReportViewer._current + length;
	if(b > data.length) {
		b = data.length;
	}
	var _g1 = a;
	var _g = b;
	while(_g1 < _g) {
		var p = _g1++;
		var info = data[p];
		var date = info.date;
		html += view_reportviewer_Html.getReport(info.id,info.member_id,{ tasks : info.task_id_list, note : info.note, images : info.image_list, dates : [utils_Data.getDate(date),utils_Data.getDay(date)], updatetime : info.updatetime, stars : info.star_list, archives : info.archived_list});
	}
	view_ReportViewer._current = b;
	return html;
};
view_ReportViewer.getReportString = function(info) {
	var memberID = info.member_id;
	var tasks = info.task_id_list.split(",");
	var date = info.date;
	var array = [db_Members.db[memberID].name,utils_Data.getDate(date),utils_Data.getDay(date),info.note];
	var _g1 = 0;
	var _g = tasks.length;
	while(_g1 < _g) {
		var q = _g1++;
		var taskID = tasks[q];
		var taskInfo = db_Tasks.db[taskID];
		if(taskInfo == null) {
			continue;
		}
		var workID = taskInfo.work_id;
		var workInfo = db_Works.db[workID];
		var clientID = workInfo.client_id;
		var clientInfo = db_Clients.db[clientID];
		array.push(workInfo.name);
		array.push(clientInfo.name);
	}
	return array.join(",");
};
view_ReportViewer.fadein = function() {
	var jReports = view_ReportViewer._jContents.find(".report").filter(".loading");
	var jArticles = jReports.find("article").css({ opacity : 0});
	var _g1 = 0;
	var _g = jArticles.length;
	while(_g1 < _g) {
		var p = _g1++;
		jReports.eq(p).removeClass("loading");
		jArticles.eq(p).stop().delay(60 * p).animate({ opacity : 1},200);
	}
};
view_ReportViewer.addNewEditor = function(myID,date) {
	jp_saken_js_utils_Ajax.getIsEmpty("reports",function(isEmpty) {
		if(!isEmpty) {
			return;
		}
		var tmp = view_ReportViewer._jContents;
		var tmp1 = utils_Data.getDate(date);
		var tmp2 = utils_Data.getDay(date);
		tmp.prepend(view_reportviewer_Html.getReport(0,myID,{ dates : [tmp1,tmp2]},true));
		var jTarget = view_ReportViewer._jContents.find(".report").first();
		view_reportviewer_AutoSave.setHTML(jTarget);
		new view_reportviewer_DragAndDrop(jTarget);
	},"date = \"" + date + "\" AND member_id = " + myID);
};
view_ReportViewer.onClick = function(event) {
	var jTarget = $(event.target);
	var jReport = jTarget.parents(".report");
	if(jTarget.hasClass("update")) {
		view_reportviewer_ReportEditor.update(jReport);
	}
	if(jTarget.hasClass("edit")) {
		view_reportviewer_ReportEditor.setEditMode(jReport);
	}
	if(jTarget.hasClass("clearTask")) {
		view_ReportViewer.clearTask(jTarget.parents(".task"));
	}
	if(jTarget.hasClass("upTask")) {
		view_ReportViewer.upTask(jTarget.parents(".task"));
	}
	if(jTarget.hasClass("downTask")) {
		view_ReportViewer.downTask(jTarget.parents(".task"));
	}
	if(jTarget.hasClass("addTask")) {
		view_ReportViewer.addTask(jReport.find(".tasks"));
	}
	if(jTarget.hasClass("copyTask")) {
		view_ReportViewer.copyTasks(jReport);
	}
	if(jTarget.hasClass("deleteImage")) {
		view_ReportViewer.deleteImage(jTarget);
	}
	if(jTarget.hasClass("addStar")) {
		view_ReportViewer.addStar(jReport);
	}
	if(jTarget.hasClass("archiveReport")) {
		view_ReportViewer.archiveReport(jReport);
	}
	if(jTarget.hasClass("search")) {
		view_reportviewer_SearchNavi.input(jTarget.text());
	}
};
view_ReportViewer.onKeyup = function(event) {
	var jTarget = $(event.target);
	var keyCode = event.keyCode;
	if(keyCode == 13) {
		view_ReportViewer.onEnter(jTarget);
	}
	if(event.ctrlKey) {
		if(keyCode == 8) {
			view_ReportViewer.clearTask(jTarget.parents(".task"));
		}
	}
};
view_ReportViewer.onChange = function(event) {
	var jTarget = $(event.target);
	view_ReportViewer.setWorkDatalist(jTarget.parents(".task"));
	view_ReportViewer.setTotaltime(jTarget.parents(".report"));
};
view_ReportViewer.onEnter = function(jTarget) {
	var jTask = jTarget.parents(".task");
	if(jTask.length == 0) {
		return;
	}
	var jSpan = jTarget.parent("span");
	var jTasks = jTarget.parents(".tasks");
	var isInputed = jTarget.prop("value").length > 0;
	if(jTask["is"](":last-child") && jSpan["is"](".hour")) {
		if(isInputed) {
			view_ReportViewer.addTask(jTasks);
		}
	} else if(isInputed) {
		var jNext = jTask.find("span").eq(jSpan.index() + 1).find("input");
		if(jNext.length > 0) {
			jNext.trigger("focus");
		} else {
			jTasks.find(".task").eq(jTask.index() + 1).find("input").first().trigger("focus");
		}
	} else if(jSpan["is"](":first-child")) {
		view_reportviewer_ReportEditor.update(jTasks.parents(".report"));
	}
};
view_ReportViewer.setWorkDatalist = function(jTask) {
	var client = jTask.find(".client").find("input").prop("value");
	var clientID = view_ReportViewer._jClientDatalist.find("[value=\"" + client + "\"]").data("id");
	if(clientID == null) {
		return;
	}
	ui_Datalist.set(view_ReportViewer._jWorkDatalist,"works",clientID);
};
view_ReportViewer.addTask = function(jTasks) {
	var jTaskList = jTasks.find(".task");
	var jFocusTask = jTaskList.filter(".lastFocus");
	if(jFocusTask.length == 0) {
		jFocusTask = jTaskList.last();
	}
	var index = jFocusTask.index();
	var scrollTop = 30 * index;
	jFocusTask.after(view_reportviewer_Html.getTasks());
	jFocusTask.next().hide().slideDown(200).find("input").first().trigger("focus").removeClass("lastFocus");
	jTasks.animate({ scrollTop : scrollTop},200);
};
view_ReportViewer.clearTask = function(jTask) {
	if(jTask.length == 0) {
		return;
	}
	var jReport = jTask.parents(".report");
	var jTasks = jTask.parents(".tasks");
	var index = jTask.index();
	if(jTasks.find(".task").length == 1) {
		if(index == 0) {
			jTask.find("input").prop("value","");
		}
	} else {
		jTask.remove();
	}
	view_ReportViewer.setTotaltime(jReport);
};
view_ReportViewer.upTask = function(jTask) {
	var jTasks = jTask.parents(".tasks");
	var index = jTask.index();
	jTasks.find(".task").eq(index - 1).before(jTask);
};
view_ReportViewer.downTask = function(jTask) {
	var jTasks = jTask.parents(".tasks");
	var index = jTask.index();
	jTasks.find(".task").eq(index + 1).after(jTask);
};
view_ReportViewer.copyTasks = function(jReport) {
	if(jReport.data("id") > 0) {
		return;
	}
	jp_saken_js_utils_Ajax.getMaxData("reports","id",function(id) {
		if(id == 0) {
			return;
		}
		jp_saken_js_utils_Ajax.getData("reports",["task_id_list"],function(data) {
			var html = view_reportviewer_Html.getTasks(data[0].task_id_list.split(","),true);
			jReport.find(".tasks").html(html);
			view_ReportViewer.setTotaltime(jReport);
		},"id = " + id);
	},"member_id = " + Manager.myID);
};
view_ReportViewer.deleteImage = function(jTarget) {
	jTarget.parents("span").addClass("hidden");
};
view_ReportViewer.addStar = function(jReport) {
	var reportID = jReport.data("id");
	var myID = Manager.myID;
	var myParmanentID = Manager.myParmanentID;
	var jStars = jReport.find(".star").find("ul");
	var where = "id = " + reportID;
	jp_saken_js_utils_Ajax.getData("reports",["star_list","is_checked_star"],function(data) {
		var info = data[0];
		var array = info.star_list ? info.star_list.split(",") : [];
		var isEmpty = array.indexOf(myID) < 0;
		var checkd = info.is_checked_star;
		var tmp = view_reportviewer_Html.getStars(array);
		jStars.html(tmp);
		if(isEmpty) {
			array.push(myID);
			jStars.append("<li class=\"mine\" title=\"" + myParmanentID + "\">★</li>");
			jStars.find("li").last().css({ top : 10}).animate({ top : 0},300,"easeOutBack");
			jReport.addClass("stared");
		} else {
			HxOverrides.remove(array,myID);
			if(array.length == 0) {
				checkd = 1;
			}
			var jMine = jStars.find(".mine");
			if(jMine.length > 0) {
				jStars.find(".mine").remove();
			} else {
				var tmp1 = view_reportviewer_Html.getStars(array);
				jStars.html(tmp1);
			}
			jReport.removeClass("stared");
		}
		var stars = array.join(",");
		view_ReportViewer.updateStars(reportID,stars);
		var columns = ["star_list","is_checked_star"];
		var values = [stars,isEmpty ? 0 : checkd];
		jp_saken_js_utils_Ajax.updateData("reports",columns,values,where);
	},where);
};
view_ReportViewer.archiveReport = function(jReport,isLoad) {
	if(isLoad == null) {
		isLoad = true;
	}
	jReport.addClass("archived");
	var reportID = jReport.data("id");
	var myID = Manager.myID;
	var where = "id = " + reportID;
	jp_saken_js_utils_Ajax.getData("reports",["archived_list"],function(data) {
		var array = data[0].archived_list ? data[0].archived_list.split(",") : [];
		array.push(myID);
		var archives = array.join(",");
		view_ReportViewer.updateArchive(reportID,archives);
		jp_saken_js_utils_Ajax.updateData("reports",["archived_list"],[archives],where);
	},where);
	if(isLoad) {
		view_ReportViewer.loadMore(1);
	}
};
view_ReportViewer.updateArchive = function(reportID,archives) {
	var _g1 = 0;
	var _g = view_ReportViewer._fullData.length;
	while(_g1 < _g) {
		var p = _g1++;
		if(view_ReportViewer._fullData[p].id == reportID) {
			view_ReportViewer._fullData[p].archived_list = archives;
		}
	}
};
var view_SimpleBoard = function() { };
view_SimpleBoard.__name__ = true;
view_SimpleBoard.init = function() {
	view_SimpleBoard._jParent = $("#simpleboard").on("click",null,view_SimpleBoard.onClick);
	view_SimpleBoard._jNewentry = view_SimpleBoard._jParent.find(".newentry");
	view_SimpleBoard._jTextarea = view_SimpleBoard._jNewentry.find("textarea").on("keydown",null,view_SimpleBoard.onKeydown);
	view_SimpleBoard._jEntries = view_SimpleBoard._jParent.find(".entries");
	view_SimpleBoard._defNewentryH = view_SimpleBoard._curNewentryH = view_SimpleBoard._jNewentry.height();
};
view_SimpleBoard.show = function() {
	view_SimpleBoard.start();
	view_SimpleBoard._jParent.fadeIn(300);
};
view_SimpleBoard.hide = function() {
	view_SimpleBoard._jParent.stop().hide();
};
view_SimpleBoard.onLoop = function() {
	if(view_SimpleBoard._lastUpdatetime == null) {
		view_SimpleBoard._lastUpdatetime = Manager.visitDatetime;
	}
	jp_saken_js_utils_Ajax.getData("simpleboard",["id"],function(data) {
		if(data.length > 0) {
			view_SimpleBoard.start();
		}
	},"updatetime > \"" + view_SimpleBoard._lastUpdatetime + "\"");
};
view_SimpleBoard.onClick = function(event) {
	var jTarget = $(event.target);
	var jParant = jTarget.parents(".entry");
	if(jTarget.hasClass("delete")) {
		view_SimpleBoard.deleteEntry(jParant);
	}
	if(jTarget.hasClass("checkbox")) {
		view_SimpleBoard.checkEntry(jParant,jTarget);
	}
};
view_SimpleBoard.onKeydown = function(event) {
	var text = view_SimpleBoard._jTextarea.prop("value");
	var lines = jp_saken_common_utils_Handy.getLines(text);
	view_SimpleBoard.setNewentryHeight(view_SimpleBoard._defNewentryH * lines);
	if(event.keyCode == 13) {
		if(event.shiftKey) {
			view_SimpleBoard.setNewentryHeight(view_SimpleBoard._curNewentryH + view_SimpleBoard._defNewentryH);
		} else if(text.length > 0) {
			view_SimpleBoard.setNewentryHeight(view_SimpleBoard._defNewentryH);
			view_SimpleBoard.addEntry(text);
			view_SimpleBoard._jTextarea.prop("value","");
			event.preventDefault();
		}
	}
};
view_SimpleBoard.setNewentryHeight = function(value) {
	view_SimpleBoard._curNewentryH = value;
	view_SimpleBoard._jNewentry.height(value);
};
view_SimpleBoard.start = function() {
	view_SimpleBoard.getDatetime(function(datetime) {
		view_SimpleBoard._checkList = [];
		view_SimpleBoard.setEntries();
	});
};
view_SimpleBoard.setEntries = function() {
	var columns = ["id","member_id","text","check_list"];
	jp_saken_js_utils_Ajax.getData("simpleboard",columns,function(data) {
		var myID = Manager.myID;
		var html = "";
		data.reverse();
		var _g1 = 0;
		var _g = data.length;
		while(_g1 < _g) {
			var p = _g1++;
			var entry = data[p];
			var id = entry.id;
			var text = entry.text;
			var memberID = entry.member_id;
			var checkList = entry.check_list.split(",");
			var isChecked = checkList.indexOf(myID) > -1;
			view_SimpleBoard._checkList[id] = checkList;
			html += view_SimpleBoard.getEntryHTML(id,memberID,jp_saken_common_utils_Handy.getAdjustedHTML(text),isChecked,checkList.length);
		}
		view_SimpleBoard._jEntries.html(html);
	},"is_visible=1");
};
view_SimpleBoard.addEntry = function(text) {
	var myID = Manager.myID;
	view_SimpleBoard.getDatetime(function(datetime) {
		var columns = ["member_id","text","updatetime","check_list"];
		jp_saken_js_utils_Ajax.insertData("simpleboard",columns,[myID,text,datetime,myID],function(lastID) {
			view_SimpleBoard._checkList[lastID] = [myID];
			var html = jp_saken_common_utils_Handy.getAdjustedHTML(text);
			var html1 = view_SimpleBoard.getEntryHTML(lastID,myID,html,true,1);
			view_SimpleBoard._jEntries.prepend(html1).find("li").eq(0).hide().slideDown(500);
		});
	});
	view_SimpleBoard._jTextarea.focus();
};
view_SimpleBoard.deleteEntry = function(jTarget) {
	var text = jp_saken_common_utils_Handy.getLimitedText(jTarget.find(".text").text());
	var isOK = window.confirm("「" + text + "」を削除してもよろしいですか？");
	if(!isOK) {
		return;
	}
	jTarget.remove();
	view_SimpleBoard.updateEntry("is_visible","0","id = " + Std.string(jTarget.data("id")));
};
view_SimpleBoard.checkEntry = function(jTarget,jCheckbox) {
	var id = jTarget.data("id");
	var myID = Manager.myID;
	var list = view_SimpleBoard._checkList[id];
	if(jCheckbox.prop("checked")) {
		list.push(myID);
	} else {
		HxOverrides.remove(list,myID);
	}
	var length = list.length + "";
	jTarget.find(".check").find("i").text(length);
	view_SimpleBoard.updateEntry("check_list",list.join(","),"id = " + id);
};
view_SimpleBoard.updateEntry = function(column,value,where) {
	view_SimpleBoard.getDatetime(function(datetime) {
		jp_saken_js_utils_Ajax.updateData("simpleboard",[column,"updatetime"],[value,datetime],where);
	});
};
view_SimpleBoard.getDatetime = function(onLoaded) {
	jp_saken_js_utils_Ajax.getDatetime(function(datetime) {
		view_SimpleBoard._lastUpdatetime = datetime;
		onLoaded(datetime);
	});
};
view_SimpleBoard.getEntryHTML = function(id,memberID,text,isChecked,checkLength) {
	var memberDB = db_Members.db[memberID];
	var isSelf = memberID == Manager.myID;
	var cls = isSelf ? " self" : "";
	var checkd = isChecked ? " checked" : "";
	var disabled = isSelf ? " disabled" : "";
	var html = "\n\t\t<li class=\"entry" + cls + "\" data-id=\"" + id + "\">\n\t\t\t<article class=\"article\">\n\t\t\t\t<input type=\"checkbox\" class=\"checkbox\"" + checkd + disabled + ">\n\t\t\t\t<b class=\"name " + Std.string(memberDB.parmanent_id) + " " + Std.string(memberDB.team) + "\">" + Std.string(memberDB.name) + "</b>\n\t\t\t\t<p class=\"text\">" + text + "</p>\n\t\t\t\t<button type=\"button\" class=\"delete\">×</button>\n\t\t\t\t<aside class=\"check\"><i>" + checkLength + "</i>人チェック済</aside>\n\t\t\t</article>\n\t\t</li>";
	return html;
};
var view_StarChecker = function() { };
view_StarChecker.__name__ = true;
view_StarChecker.init = function() {
	Manager.jWindow().on("click",null,view_StarChecker.onClickWindow);
	view_StarChecker._jParent = $("#starchecker").on("click",null,view_StarChecker.onClick);
	view_StarChecker._jContent = view_StarChecker._jParent.find("#starchecker-content");
	view_StarChecker._jFavicon = $("link.favicon");
	view_StarChecker._isOpen = false;
};
view_StarChecker.show = function() {
	view_StarChecker._jParent.fadeIn(300);
};
view_StarChecker.hide = function() {
	view_StarChecker.close();
	view_StarChecker.unset();
	view_StarChecker._lastData = null;
	view_StarChecker._jContent.empty();
	view_StarChecker._jParent.stop().hide();
};
view_StarChecker.onLoop = function() {
	jp_saken_js_utils_Ajax.getData("reports",["id","date","star_list"],function(data) {
		var length = data.length;
		if(length > 0) {
			view_StarChecker.set(data);
		}
		view_StarChecker._lastData = data;
	},"is_checked_star = 0 AND member_id = " + Manager.myID);
};
view_StarChecker.set = function(data) {
	if(view_StarChecker.getIsSame(data,view_StarChecker._lastData)) {
		return;
	}
	view_StarChecker._jParent.addClass("no-checked");
	view_StarChecker._jFavicon.prop("href","files/img/favicon_on.ico");
	var html = "";
	var myName = Manager.myName;
	var _g1 = 0;
	var _g = data.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info = data[p];
		if(info.star_list.length == 0) {
			continue;
		}
		var id = info.id;
		var date = utils_Data.getDate(info.date);
		var stars = info.star_list.split(",");
		var length = stars.length;
		var search = myName + "," + date;
		var member1 = view_StarChecker.getMemberName(db_Members.db[stars[length - 1]]);
		var member2 = view_StarChecker.getMemberName(db_Members.db[stars[length - 2]]);
		var others = "";
		if(member2.length > 0) {
			member2 = "と" + member2;
		}
		if(length > 2) {
			others = "他" + (length - 2) + "名";
		}
		var string = "あなたの" + date + "の日報に" + member1 + member2 + others + "がスターを付けてます";
		html += "<li data-id=\"" + id + "\"><a class=\"search\" data-search=\"" + search + "\">" + string + "</a></li>";
		view_ReportViewer.updateStars(id,info.star_list);
	}
	view_StarChecker._jContent.html(html);
};
view_StarChecker.getMemberName = function(db) {
	if(db == null) {
		return "";
	}
	var name = db.name;
	return (name == null ? "名無し" : name.split(" ")[0]) + "さん";
};
view_StarChecker.unset = function() {
	view_StarChecker._jParent.removeClass("no-checked");
	view_StarChecker._jFavicon.prop("href","files/img/favicon.ico");
};
view_StarChecker.getIsSame = function(a,b) {
	if(view_StarChecker._lastData == null) {
		return false;
	}
	if(a.length != b.length) {
		return false;
	}
	var _g1 = 0;
	var _g = a.length;
	while(_g1 < _g) {
		var p = _g1++;
		var starA = a[p].star_list.split(",");
		var starB = b[p].star_list.split(",");
		if(starA[starA.length - 1] != starB[starB.length - 1]) {
			return false;
		}
	}
	return true;
};
view_StarChecker.onClick = function(event) {
	if(!view_StarChecker._jParent.hasClass("no-checked")) {
		return;
	}
	var jTarget = $(event.target);
	if(jTarget.hasClass("button")) {
		view_StarChecker.toggleButton();
	}
	if(jTarget.hasClass("search")) {
		view_StarChecker.jump(jTarget);
	}
};
view_StarChecker.onClickWindow = function(event) {
	var jTarget = $(event.target);
	if(jTarget.parents("#starchecker").length > 0) {
		return;
	}
	view_StarChecker.close();
};
view_StarChecker.toggleButton = function() {
	if(view_StarChecker._isOpen) {
		view_StarChecker.close();
	} else {
		view_StarChecker.open();
	}
};
view_StarChecker.open = function() {
	view_StarChecker._isOpen = true;
	view_StarChecker._jContent.stop(true,true).slideDown(100);
};
view_StarChecker.close = function() {
	view_StarChecker._isOpen = false;
	view_StarChecker._jContent.stop(true,true).slideUp(100);
};
view_StarChecker.jump = function(jTarget) {
	var jParent = jTarget.parents("li");
	jp_saken_js_utils_Ajax.updateData("reports",["is_checked_star"],[1],"id = " + Std.string(jParent.data("id")));
	view_reportviewer_SearchNavi.input(jTarget.data("search"));
	jParent.remove();
	if(view_StarChecker._jContent.find("li").length == 0) {
		view_StarChecker.unset();
		view_StarChecker.close();
	}
};
var view_reportviewer_AutoSave = function() { };
view_reportviewer_AutoSave.__name__ = true;
view_reportviewer_AutoSave.init = function(jParent) {
	view_reportviewer_AutoSave._jParent = jParent;
};
view_reportviewer_AutoSave.onLoop = function() {
	var jReport = view_reportviewer_AutoSave._jParent.find(".report.edit-mode[data-id=\"0\"]");
	if(jReport.length == 0) {
		return;
	}
	var tasks = view_reportviewer_AutoSave.getTasks(jReport);
	var images = view_reportviewer_AutoSave.getImages(jReport);
	var note = jp_saken_common_utils_Handy.getReplacedSC(jReport.find(".note").find("textarea").prop("value"));
	var columns = ["tasks","note","images"];
	var values = [tasks,note,images];
	var joinData = values.join("+");
	if(view_reportviewer_AutoSave._joinData == joinData) {
		return;
	}
	view_reportviewer_AutoSave._joinData = joinData;
	view_reportviewer_AutoSave.update(Manager.myID,columns,values);
};
view_reportviewer_AutoSave.unsetData = function(jReport) {
	if(jReport.data("id") > 0) {
		return;
	}
	jp_saken_js_utils_Ajax.updateData("autosaves",["tasks","note","images"],["","",""],"member_id = " + Manager.myID);
};
view_reportviewer_AutoSave.setHTML = function(jReport) {
	jp_saken_js_utils_Ajax.getData("autosaves",["tasks","note","images"],function(data) {
		if(data.length == 0) {
			return;
		}
		var info = data[0];
		var tasks = info.tasks;
		var note = info.note;
		var images = info.images;
		if((tasks + note + images).length == 0) {
			return;
		}
		jReport.find(".tasks").html(view_reportviewer_AutoSave.getTasksHTML(tasks.split("\n")));
		jReport.find(".note").find("textarea").prop("value",note);
		jReport.find(".image").find("figure").html(view_reportviewer_AutoSave.getImagesHTML(images.split("\n")));
		view_ReportViewer.setTotaltime(jReport);
	},"member_id = " + Manager.myID);
};
view_reportviewer_AutoSave.getTasks = function(jReport) {
	var array = [];
	var jTasks = jReport.find(".tasks").find(".task");
	var _g1 = 0;
	var _g = jTasks.length;
	while(_g1 < _g) {
		var i = _g1++;
		var jTarget = jTasks.eq(i);
		var client = jTarget.find(".client").find("input").prop("value");
		var work = jTarget.find(".work").find("input").prop("value");
		var hour = jTarget.find(".hour").find("input").prop("value");
		array.push(client + "," + work + "," + hour);
	}
	return array.join("\n");
};
view_reportviewer_AutoSave.getImages = function(jReport) {
	var array = [];
	var jList = jReport.find(".image").find("figure").find("span").filter(":visible");
	var _g1 = 0;
	var _g = jList.length;
	while(_g1 < _g) {
		var i = _g1++;
		var jTarget = jList.eq(i);
		var filename = jTarget.data("filename");
		var src = jTarget.find("img").prop("src");
		array.push(filename + "#-----#" + src);
	}
	return array.join("\n");
};
view_reportviewer_AutoSave.update = function(myID,columns,values) {
	jp_saken_js_utils_Ajax.getIsEmpty("autosaves",function(isEmpty) {
		if(isEmpty) {
			columns.unshift("member_id");
			values.unshift(myID);
			jp_saken_js_utils_Ajax.insertData("autosaves",columns,values);
		} else {
			jp_saken_js_utils_Ajax.updateData("autosaves",columns,values,"member_id = " + myID);
		}
	},"member_id = " + myID);
};
view_reportviewer_AutoSave.getTasksHTML = function(tasks) {
	var html = "";
	var _g1 = 0;
	var _g = tasks.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info = tasks[p];
		if(info.length == 0) {
			continue;
		}
		var array = info.split(",");
		html += view_reportviewer_Html.getTask([0,0,array[0],0,array[1],array[2]]);
	}
	return html;
};
view_reportviewer_AutoSave.getImagesHTML = function(images) {
	var html = "";
	var _g1 = 0;
	var _g = images.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info = images[p];
		if(info.length == 0) {
			continue;
		}
		var array = info.split("#-----#");
		var src = array[1];
		var image = new Image();
		image.src = src;
		html += view_reportviewer_Html.getImage(array[0],src.split(";base64,")[1],image);
	}
	return html;
};
var view_reportviewer_DragAndDrop = function(jParent) {
	this._onInner = false;
	this._jParent = jParent.on({ drop : $bind(this,this.onDrop), dragenter : $bind(this,this.onEnter), dragover : $bind(this,this.onOver), dragleave : $bind(this,this.onLeave)});
};
view_reportviewer_DragAndDrop.__name__ = true;
view_reportviewer_DragAndDrop.prototype = {
	onDrop: function(event) {
		var _gthis = this;
		var file = event.originalEvent.dataTransfer.files[0];
		var fileReader = new FileReader();
		var fileType = file.type.split("image/")[1];
		if(fileType == "jpeg") {
			fileType = "jpg";
		}
		fileReader.onload = function(event1) {
			_gthis.onLoaded(event1.target.result,fileType);
		};
		fileReader.readAsDataURL(file);
		this._jParent.removeClass("dragging");
		this.cancel(event);
		event.preventDefault();
	}
	,onLoaded: function(src,fileType) {
		var _gthis = this;
		var image = new Image();
		image.src = src;
		image.onload = function(event) {
			if(image.width > 1200 || image.height > 960) {
				jp_saken_js_utils_Handy.alert("ファイルサイズが大き過ぎます。\nリサイズして再度お試しください。");
				return;
			}
			var filename = new Date().getTime() + "." + fileType;
			var base64 = src.split(";base64,")[1];
			_gthis._jParent.find(".image").find("figure").append(view_reportviewer_Html.getImage(filename,base64,image));
		};
	}
	,onEnter: function(event) {
		this._onInner = true;
		this.cancel(event);
	}
	,onOver: function(event) {
		this._onInner = false;
		this._jParent.addClass("dragging");
		this.cancel(event);
	}
	,onLeave: function(event) {
		if(this._onInner) {
			this._onInner = false;
		} else {
			this._jParent.removeClass("dragging");
		}
		this.cancel(event);
	}
	,cancel: function(event) {
		event.preventDefault();
		event.stopPropagation();
	}
};
var view_reportviewer_Html = function() { };
view_reportviewer_Html.__name__ = true;
view_reportviewer_Html.getReport = function(id,memberID,info,isEditMode) {
	if(isEditMode == null) {
		isEditMode = false;
	}
	var memberDB = db_Members.db[memberID];
	if(memberDB.is_visible == 0) {
		return "";
	}
	var myID = Manager.myID;
	var isSelf = memberID == myID;
	var cls = isSelf ? "self " : "";
	if(isEditMode) {
		cls += "edit-mode ";
	}
	var tasks = info.tasks ? info.tasks.split(",") : null;
	var dates = info.dates;
	var date = dates[0];
	var day = dates[1];
	var note = info.note ? info.note : "";
	var images = info.images ? info.images.split(",") : [];
	var updatetime = info.updatetime ? info.updatetime : "1999-01-01";
	var starts = info.stars ? info.stars.split(",") : [];
	var archives = info.archives ? info.archives.split(",") : [];
	var team = memberDB.team;
	var myParmanentID = Manager.myParmanentID;
	if(starts.indexOf(myID) > -1) {
		cls += "stared ";
	}
	if(archives.indexOf(myID) > -1) {
		cls += "archived ";
	}
	if(team.length == 0) {
		team = memberDB.section;
	}
	var html = "\n\t\t<li class=\"report " + cls + team + " loading\" data-id=\"" + id + "\">\n\t\t\t<article>\n\t\t\t\t<header class=\"header\">\n\t\t    \t\t<p class=\"name\"><a class=\"search\">" + Std.string(memberDB.name) + "</a></p>\n\t\t\t\t\t<aside>\n\t\t\t\t\t\t<time datetime=\"" + date + "\" class=\"datetime\"><a class=\"search\">" + date + "</a> <a class=\"search\">" + day + "</a></time>\n\t\t\t\t\t\t<button type=\"button\" class=\"edit\">編集</button>\n\t\t\t\t\t</aside>\n\t\t    \t</header>\n\t\t    \t<ul class=\"tasks\">" + view_reportviewer_Html.getTasks(tasks) + "</ul>" + view_reportviewer_Html.getTotaltime(tasks) + "\n\t\t\t\t<button type=\"button\" class=\"addTask\">+</button>\n\t\t\t\t<button type=\"button\" class=\"copyTask\">■</button>\n\t\t    \t<aside class=\"note\">\n\t\t    \t\t<p><textarea placeholder=\"今日のひとこと\">" + note + "</textarea><em>" + jp_saken_common_utils_Handy.getAdjustedHTML(note) + "</em></p>\n\t\t    \t</aside>\n\t\t    \t<aside class=\"image\">\n\t\t\t\t\t<p>画像をドロップしてください</p>\n\t\t    \t\t<figure>" + view_reportviewer_Html.getImages(images) + "</figure>\n\t\t    \t</aside>\n\t\t    \t<button type=\"button\" class=\"update\">&nbsp;</button>\n\t\t    \t<footer class=\"footer\">\n\t\t    \t\t<section class=\"star\">\n\t\t        \t\t<button type=\"button\" class=\"addStar\">★</button>\n\t\t        \t\t<ul>" + view_reportviewer_Html.getStars(starts) + "</ul>\n\t\t    \t\t</section>\n\t\t    \t\t<time datetime=\"" + utils_Data.getDate(updatetime) + "\" class=\"lastupdate\">" + Std.string(HxOverrides.strDate(updatetime)) + "</time>\n\t\t    \t\t<button type=\"button\" class=\"archiveReport\">×</button>\n\t\t    \t</footer>\n\t\t\t</article>\n\t\t</li>";
	return html;
};
view_reportviewer_Html.getTasks = function(tasks,isCopy) {
	if(isCopy == null) {
		isCopy = false;
	}
	var html = "";
	if(tasks == null) {
		tasks = [0];
	}
	var _g1 = 0;
	var _g = tasks.length;
	while(_g1 < _g) {
		var p = _g1++;
		var taskID = tasks[p];
		if(taskID > 0) {
			var taskInfo = db_Tasks.db[taskID];
			var workID = taskInfo.work_id;
			var workInfo = db_Works.db[workID];
			var clientID = workInfo.client_id;
			var clientInfo = db_Clients.db[clientID];
			html += view_reportviewer_Html.getTask([isCopy ? "0" : taskID,clientID,clientInfo.name,workID,workInfo.name,taskInfo.hour]);
		} else {
			html += view_reportviewer_Html.getTask(null);
		}
	}
	return html;
};
view_reportviewer_Html.getTask = function(info) {
	var taskID;
	var clientID;
	var clientName;
	var workID;
	var workName;
	var hour;
	if(view_reportviewer_Html._taskCounter == null) {
		view_reportviewer_Html._taskCounter = 0;
	}
	view_reportviewer_Html._taskCounter++;
	if(info == null) {
		workID = "0";
		clientID = workID;
		taskID = clientID;
		hour = "";
		workName = hour;
		clientName = workName;
	} else {
		taskID = info[0];
		clientID = info[1];
		clientName = info[2];
		workID = info[3];
		workName = info[4];
		hour = info[5];
	}
	var clientDatalistID = "clientDatalist-" + view_reportviewer_Html._taskCounter;
	var workDatalistID = "workDatalist" + view_reportviewer_Html._taskCounter;
	return "\n\t\t\t<li class=\"task\" data-id=\"" + taskID + "\">\n\t\t    \t<span class=\"client\" data-id=\"" + clientID + "\">\n\t\t\t\t\t<input type=\"search\" autocomplete=\"on\" placeholder=\"クライアント名\" value=\"" + clientName + "\" list=\"client-datalist\">\n\t\t\t\t\t<em><a class=\"search\">" + clientName + "</a></em>\n\t\t\t\t</span>\n\t\t    \t<span class=\"work\" data-id=\"" + workID + "\">\n\t\t\t\t\t<input type=\"search\" autocomplete=\"on\" placeholder=\"案件名\" value=\"" + workName + "\" list=\"work-datalist\">\n\t\t\t\t\t<em><a class=\"search\">" + workName + "</a></em>\n\t\t\t\t</span>\n\t\t    \t<span class=\"hour\">\n\t\t\t\t\t<input type=\"number\" min=\"0.5\" step=\"0.5\" placeholder=\"時間\" value=\"" + hour + "\">\n\t\t\t\t\t<em>" + hour + "</em>\n\t\t\t\t</span>\n\t\t\t\t<button type=\"button\" class=\"clearTask\">×</button>\n\t\t\t\t<button type=\"button\" class=\"upTask\">↑</button>\n\t\t\t\t<button type=\"button\" class=\"downTask\">↓</button>\n\t\t    </li>";
};
view_reportviewer_Html.getImage = function(filename,base64,image) {
	if(base64 == null) {
		base64 = "";
	}
	var fileURL = "files/upload/" + filename;
	var jWrap = $("<span data-filename=\"" + filename + "\" data-base64=\"" + base64 + "\">");
	var jAnchor = jWrap.html("<a class=\"lightbox\"></a>").find("a");
	if(image == null) {
		jAnchor.prop("href",fileURL).html("<img src=\"" + fileURL + "\">");
	} else {
		jAnchor.append(image);
	}
	jWrap.append("<button type=\"button\" class=\"deleteImage\">×</button>");
	return $("<div>").append(jWrap).html();
};
view_reportviewer_Html.getStars = function(stars) {
	var html = "";
	var length = stars.length;
	if(length > 20) {
		return "<li>★×" + length + "</li>";
	}
	var membersDB = db_Members.db;
	var myID = Manager.myID;
	var _g1 = 0;
	var _g = length;
	while(_g1 < _g) {
		var p = _g1++;
		var id = stars[p];
		var cls = id == myID ? " class=\"mine\"" : "";
		var member = membersDB[id];
		if(member == null) {
			continue;
		}
		html += "<li" + cls + " title=\"" + Std.string(member.parmanent_id) + "\">★<span class=\"starName\">" + Std.string(member.parmanent_id) + "</span></li>";
	}
	return html;
};
view_reportviewer_Html.getTotaltime = function(tasks) {
	var totaltime = 0;
	if(tasks == null) {
		tasks = [0];
	}
	var _g1 = 0;
	var _g = tasks.length;
	while(_g1 < _g) {
		var p = _g1++;
		var taskID = tasks[p];
		if(taskID > 0) {
			totaltime += parseFloat(db_Tasks.db[taskID].hour);
		}
	}
	totaltime = Math.ceil(totaltime * 10) / 10;
	return "<p class=\"totaltime\"><span>" + totaltime + "</span>h</p>";
};
view_reportviewer_Html.getDatalist = function(data) {
	var html = "";
	var _g1 = 0;
	var _g = data.length;
	while(_g1 < _g) {
		var p = _g1++;
		var info = data[p];
		if(info != null) {
			var clientID = info.client_id;
			var prop = clientID == null ? "" : " data-clientid=\"" + clientID + "\"";
			html += "<option value=\"" + Std.string(info.name) + "\" data-id=\"" + Std.string(info.id) + "\"" + prop + "></option>";
		}
	}
	return html;
};
view_reportviewer_Html.getImages = function(images) {
	var html = "";
	var _g1 = 0;
	var _g = images.length;
	while(_g1 < _g) {
		var p = _g1++;
		html += view_reportviewer_Html.getImage(images[p]);
	}
	return html;
};
var view_reportviewer_ReportEditor = function() { };
view_reportviewer_ReportEditor.__name__ = true;
view_reportviewer_ReportEditor.update = function(jParent) {
	if(view_reportviewer_ReportEditor._isUpdating) {
		window.alert("更新中です。");
		return;
	}
	view_reportviewer_ReportEditor._jParent = jParent;
	view_reportviewer_ReportEditor._jTasks = view_reportviewer_ReportEditor._jParent.find(".tasks");
	view_reportviewer_ReportEditor._jTaskList = view_reportviewer_ReportEditor._jTasks.find(".task");
	if(!view_reportviewer_ReportEditor.getIsFull()) {
		window.alert("空欄があります。");
		return;
	}
	view_reportviewer_ReportEditor._isUpdating = true;
	view_reportviewer_ReportEditor._jParent.addClass("updating").unbind().find("article").stop().css({ opacity : .3});
	view_reportviewer_ReportEditor.updateTasks();
	view_reportviewer_ReportEditor.updateImages();
};
view_reportviewer_ReportEditor.setEditMode = function(jParent) {
	new view_reportviewer_DragAndDrop(jParent);
	jParent.stop().addClass("edit-mode").animate({ width : 628},300);
	jParent.find("article").stop().css({ opacity : .3}).animate({ opacity : 1},1000);
};
view_reportviewer_ReportEditor.cancel = function() {
	view_reportviewer_ReportEditor._isUpdating = false;
	view_reportviewer_ReportEditor._jParent.stop().removeClass("updating");
	view_reportviewer_ReportEditor._jParent.find("article").stop().animate({ opacity : 1},300);
	view_reportviewer_ReportEditor._jTaskList.unbind();
};
view_reportviewer_ReportEditor.getIsFull = function() {
	if(view_reportviewer_ReportEditor._jTaskList.length > 1) {
		var _g1 = 0;
		var _g = view_reportviewer_ReportEditor._jTaskList.length;
		while(_g1 < _g) {
			var p = _g1++;
			var jTask = view_reportviewer_ReportEditor._jTaskList.eq(p);
			var isEmpty = true;
			var jInputs = jTask.find("input");
			var _g3 = 0;
			var _g2 = jInputs.length;
			while(_g3 < _g2) {
				var i = _g3++;
				if(jInputs.eq(i).prop("value").length > 0) {
					isEmpty = false;
				}
			}
			if(isEmpty) {
				jTask.remove();
			}
		}
	}
	view_reportviewer_ReportEditor._jTaskList = view_reportviewer_ReportEditor._jTasks.find(".task");
	var isFull = true;
	var jInputs1 = view_reportviewer_ReportEditor._jTaskList.find("input");
	var _g11 = 0;
	var _g4 = jInputs1.length;
	while(_g11 < _g4) {
		var i1 = _g11++;
		if(jInputs1.eq(i1).prop("value").length == 0) {
			isFull = false;
		}
	}
	return isFull;
};
view_reportviewer_ReportEditor.updateTasks = function() {
	var counter = view_reportviewer_ReportEditor._jTaskList.length;
	var onUpdated = function(event) {
		counter -= 1;
		if(counter == 0) {
			view_reportviewer_ReportEditor.updateData();
		}
	};
	var _g1 = 0;
	var _g = counter;
	while(_g1 < _g) {
		var p = _g1++;
		var jTask = view_reportviewer_ReportEditor._jTaskList.eq(p).unbind().on("updated",null,onUpdated);
		new view_reportviewer_Task(jTask);
	}
};
view_reportviewer_ReportEditor.updateImages = function() {
	var jImages = view_reportviewer_ReportEditor._jParent.find(".image").find("figure").find("span");
	if(jImages.length == 0) {
		return;
	}
	var _g1 = 0;
	var _g = jImages.length;
	while(_g1 < _g) {
		var p = _g1++;
		var jTarget = jImages.eq(p);
		var filename = jTarget.data("filename");
		if(jTarget.hasClass("hidden")) {
			jTarget.remove();
			jp_saken_js_utils_Ajax.deleteImage(filename);
		} else {
			var base64 = jTarget.data("base64");
			if(base64.length > 0) {
				jp_saken_js_utils_Ajax.uploadImage(filename,base64);
				jTarget.find(".lightbox").prop("href","files/upload/" + filename);
			}
		}
	}
};
view_reportviewer_ReportEditor.updateData = function() {
	var id = view_reportviewer_ReportEditor._jParent.data("id");
	var jNote = view_reportviewer_ReportEditor._jParent.find(".note");
	var jImages = view_reportviewer_ReportEditor._jParent.find(".image").find("figure").find("span");
	var note = jp_saken_common_utils_Handy.getReplacedSC(jNote.find("textarea").prop("value"));
	var taskIDs = [];
	var images = [];
	var _g1 = 0;
	var _g = view_reportviewer_ReportEditor._jTaskList.length;
	while(_g1 < _g) {
		var p = _g1++;
		var tmp = view_reportviewer_ReportEditor._jTaskList.eq(p).data("id");
		taskIDs.push(tmp);
	}
	var _g11 = 0;
	var _g2 = jImages.length;
	while(_g11 < _g2) {
		var p1 = _g11++;
		var tmp1 = jImages.eq(p1).data("filename");
		images.push(tmp1);
	}
	jNote.find("em").html(jp_saken_common_utils_Handy.getAdjustedHTML(note));
	jp_saken_js_utils_Ajax.getDatetime(function(datetime) {
		var colums = view_reportviewer_ReportEditor.COLUMN_LIST;
		var values = Manager.myID;
		var values1 = taskIDs.join(",");
		var values2 = images.join(",");
		var values3 = [values,values1,note,values2,datetime,""];
		view_reportviewer_ReportEditor._jParent.find(".lastupdate").text(Std.string(HxOverrides.strDate(datetime)));
		if(id > 0) {
			jp_saken_js_utils_Ajax.updateData("reports",colums,values3,"id = " + id,view_reportviewer_ReportEditor.onUpdated);
		} else {
			colums = colums.concat(["date"]);
			values3.push(datetime);
			jp_saken_js_utils_Ajax.insertData("reports",colums,values3,view_reportviewer_ReportEditor.onInsertedData);
		}
	});
};
view_reportviewer_ReportEditor.onInsertedData = function(lastID) {
	view_reportviewer_ReportEditor._jParent.data("id",lastID);
	view_reportviewer_ReportEditor.onUpdated();
};
view_reportviewer_ReportEditor.onUpdated = function() {
	view_reportviewer_ReportEditor._isUpdating = false;
	var classes = "edit-mode" + " " + "updating";
	view_reportviewer_ReportEditor._jParent.stop().removeClass(classes).animate({ width : 298},300);
	view_reportviewer_ReportEditor._jParent.find("article").stop().animate({ opacity : 1},1000);
	view_reportviewer_AutoSave.unsetData(view_reportviewer_ReportEditor._jParent);
};
var view_reportviewer_Scrollbar = function() { };
view_reportviewer_Scrollbar.__name__ = true;
view_reportviewer_Scrollbar.init = function(jTarget) {
	view_reportviewer_Scrollbar._jTarget = jTarget;
	Manager.jWindow().on("scroll",null,view_reportviewer_Scrollbar.onScroll);
};
view_reportviewer_Scrollbar.onScroll = function(event) {
	var y = Manager.jWindow().scrollTop();
	var t = view_reportviewer_Scrollbar._jTarget.position().top + view_reportviewer_Scrollbar._jTarget.height();
	var h = view_reportviewer_Scrollbar._jTarget.find(".report").first().height();
	if(y - t > 100 - h * 2) {
		view_ReportViewer.loadMore();
	}
};
var view_reportviewer_SearchNavi = function() { };
view_reportviewer_SearchNavi.__name__ = true;
view_reportviewer_SearchNavi.init = function(jParent) {
	view_reportviewer_SearchNavi._jInput = jParent.find("input").on("keydown",null,view_reportviewer_SearchNavi.onKeydown);
	jParent.find(".clear").on("click",null,view_reportviewer_SearchNavi.clear);
};
view_reportviewer_SearchNavi.input = function(value) {
	view_reportviewer_SearchNavi._jInput.prop("value",value);
	view_ReportViewer.search(value);
	view_reportviewer_SortNavi.clear();
};
view_reportviewer_SearchNavi.clear = function(event) {
	view_reportviewer_SearchNavi._jInput.prop("value","");
};
view_reportviewer_SearchNavi.onKeydown = function(event) {
	if(event.keyCode == 13) {
		view_ReportViewer.search(view_reportviewer_SearchNavi._jInput.prop("value"));
		event.preventDefault();
	}
};
var view_reportviewer_SortNavi = function() { };
view_reportviewer_SortNavi.__name__ = true;
view_reportviewer_SortNavi.init = function(jParent) {
	view_reportviewer_SortNavi._jButtons = jParent.find("button").on("mousedown",null,view_reportviewer_SortNavi.onMousedown);
};
view_reportviewer_SortNavi.showNew = function() {
	view_reportviewer_SortNavi._jButtons.filter(".new").trigger("mousedown");
};
view_reportviewer_SortNavi.clear = function() {
	view_reportviewer_SortNavi._jButtons.removeClass("active");
};
view_reportviewer_SortNavi.onMousedown = function(event) {
	var jTarget = $(event.target);
	if(jTarget.hasClass("active")) {
		return;
	}
	view_reportviewer_SearchNavi.clear();
	var jParent = jTarget.parents("ul");
	jParent.find("button").removeClass("active");
	var cls = jTarget.prop("class");
	jTarget.addClass("active");
	view_ReportViewer.showReports(cls);
};
var view_reportviewer_Task = function(jParent) {
	var _gthis = this;
	this._jParent = jParent;
	this._id = jParent.data("id");
	var jClient = jParent.find(".client");
	var jWork = jParent.find(".work");
	var jHour = jParent.find(".hour");
	this._clientName = jClient.find("input").prop("value");
	this._workName = jWork.find("input").prop("value");
	this._hour = jHour.find("input").prop("value");
	this._jParent.on({ getWorkID : function(event) {
		_gthis.update();
	}, getClientID : function(event1) {
		_gthis.judgeIsEmpty("works",_gthis._workName,"案件");
	}});
	jClient.find(".search").text(this._clientName);
	jWork.find(".search").text(this._workName);
	jHour.find("em").text(this._hour);
	this.judgeIsEmpty("clients",this._clientName,"クライアント");
};
view_reportviewer_Task.__name__ = true;
view_reportviewer_Task.prototype = {
	judgeIsEmpty: function(table,name,string) {
		var _gthis = this;
		var tmp = this.getWhere(name,table == "works");
		jp_saken_js_utils_Ajax.getIsEmpty(table,function(isEmpty) {
			if(isEmpty) {
				_gthis.addData(table,name,string);
			} else {
				_gthis.getData(table,name);
			}
		},tmp);
	}
	,addData: function(table,name,string) {
		var _gthis = this;
		jp_saken_js_utils_Handy.confirm(string + "に「" + name + "」を追加しますか？",function() {
			var columns = [];
			var values = [];
			if(table == "clients") {
				columns = ["name"];
				values = [name];
			} else if(table == "works") {
				columns = ["client_id,name"];
				values = [_gthis._clientID,name];
			}
			jp_saken_js_utils_Ajax.insertData(table,columns,values,function(lastID) {
				_gthis.getData(table,name);
			});
		},function() {
			view_reportviewer_ReportEditor.cancel();
		});
	}
	,getData: function(table,name) {
		var _gthis = this;
		var tmp = this.getWhere(name,table == "works");
		jp_saken_js_utils_Ajax.getData(table,["id"],function(data) {
			if(table == "clients") {
				_gthis._clientID = data[0].id;
				_gthis._jParent.trigger("getClientID");
			} else if(table == "works") {
				_gthis._workID = data[0].id;
				_gthis._jParent.trigger("getWorkID");
			}
		},tmp);
	}
	,getWhere: function(name,isWork) {
		var where = "name = \"" + name + "\"";
		if(isWork) {
			where += " AND client_id = \"" + this._clientID + "\"";
		}
		return where;
	}
	,update: function() {
		var _gthis = this;
		jp_saken_js_utils_Ajax.getDatetime(function(datetime) {
			var myID = Manager.myID;
			var table = "tasks";
			var columns = ["member_id","work_id","hour","updatetime"];
			var values = [myID,_gthis._workID,_gthis._hour,datetime];
			if(_gthis._id > 0) {
				jp_saken_js_utils_Ajax.updateData(table,columns,values,"id = " + _gthis._id,function() {
					_gthis._jParent.trigger("updated");
				});
			} else {
				jp_saken_js_utils_Ajax.insertData(table,columns,values,function(lastID) {
					_gthis._jParent.data("id",lastID).trigger("updated");
				});
			}
		});
	}
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.__name__ = true;
Array.__name__ = true;
Date.__name__ = ["Date"];
var __map_reserved = {}
db_Clients.TABLE_NAME = "clients";
db_Clients.COLUMN_LIST = ["id","name"];
db_Members.TABLE_NAME = "members";
db_Members.COLUMN_LIST = ["id","parmanent_id","name","section","team","is_visible"];
db_Tasks.TABLE_NAME = "tasks";
db_Tasks.COLUMN_LIST = ["id","member_id","work_id","hour"];
db_Works.TABLE_NAME = "works";
db_Works.COLUMN_LIST = ["id","client_id","name"];
jp_saken_common_utils_API._path = "/api/";
jp_saken_js_components_Lightbox.ID = "lightbox";
jp_saken_js_utils_Ajax.PATH = "files/php/";
jp_saken_js_utils_Handy._window = window;
utils_Data.DAY_LIST = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
utils_Data.UPLOAD_FOLDER = "files/upload/";
view_Login.COOKIE_NAME = "DR2LoginHistory2";
view_ReportViewer.TABLE_NAME = "reports";
view_ReportViewer.LENGTH_AT_ONCE = 10;
view_SimpleBoard.TABLE_NAME = "simpleboard";
view_StarChecker.TABLE_NAME = "reports";
view_StarChecker.FAVICON_OFF = "files/img/favicon.ico";
view_StarChecker.FAVICON_ON = "files/img/favicon_on.ico";
view_reportviewer_AutoSave.TABLE_NAME = "autosaves";
view_reportviewer_DragAndDrop.MAX_IMAGE_WIDTH = 1200;
view_reportviewer_DragAndDrop.MAX_IMAGE_HEIGHT = 960;
view_reportviewer_ReportEditor.TABLE_NAME = "reports";
view_reportviewer_ReportEditor.COLUMN_LIST = ["member_id","task_id_list","note","image_list","updatetime","archived_list"];
view_reportviewer_ReportEditor.EDIT_MODE_CLASS = "edit-mode";
view_reportviewer_ReportEditor.UPDATING_CLASS = "updating";
view_reportviewer_ReportEditor.READ_MODE_WIDTH = 298;
view_reportviewer_ReportEditor.EDIT_MODE_WIDTH = 628;
Main.main();
})();
